//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTest.MyCardNoSetWCF {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyCardNoSetWCF.IService1")]
    public interface IService1 {
        
        // CODEGEN: 參數 'View_MyCard_SaveByCardBetweenQueryResult' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/View_MyCard_SaveByCardBetweenQuery", ReplyAction="http://tempuri.org/IService1/View_MyCard_SaveByCardBetweenQueryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SimpleTest.MyCardNoSetWCF.View_MyCard_SaveByCardBetweenQueryResponse View_MyCard_SaveByCardBetweenQuery(SimpleTest.MyCardNoSetWCF.View_MyCard_SaveByCardBetweenQueryRequest request);
        
        // CODEGEN: 參數 'MyCard_SaveByCardBetweenInsertResult' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MyCard_SaveByCardBetweenInsert", ReplyAction="http://tempuri.org/IService1/MyCard_SaveByCardBetweenInsertResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenInsertResponse MyCard_SaveByCardBetweenInsert(SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenInsertRequest request);
        
        // CODEGEN: 參數 'MyCard_SaveByCardBetweenUpdateResult' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MyCard_SaveByCardBetweenUpdate", ReplyAction="http://tempuri.org/IService1/MyCard_SaveByCardBetweenUpdateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenUpdateResponse MyCard_SaveByCardBetweenUpdate(SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenUpdateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MyCardNoSetWCF")]
    public partial class ReturnValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataSet returnDataSetField;
        
        private string returnMsgField;
        
        private int returnMsgNoField;
        
        private bool returnMsgNoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Data.DataSet ReturnDataSet {
            get {
                return this.returnDataSetField;
            }
            set {
                this.returnDataSetField = value;
                this.RaisePropertyChanged("ReturnDataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ReturnMsg {
            get {
                return this.returnMsgField;
            }
            set {
                this.returnMsgField = value;
                this.RaisePropertyChanged("ReturnMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ReturnMsgNo {
            get {
                return this.returnMsgNoField;
            }
            set {
                this.returnMsgNoField = value;
                this.RaisePropertyChanged("ReturnMsgNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnMsgNoSpecified {
            get {
                return this.returnMsgNoFieldSpecified;
            }
            set {
                this.returnMsgNoFieldSpecified = value;
                this.RaisePropertyChanged("ReturnMsgNoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MyCardNoSetWCF")]
    public partial class ReturnValueIns : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataSet returnDataSetField;
        
        private string returnMsgField;
        
        private int returnMsgNoField;
        
        private bool returnMsgNoFieldSpecified;
        
        private int returnSnField;
        
        private bool returnSnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Data.DataSet ReturnDataSet {
            get {
                return this.returnDataSetField;
            }
            set {
                this.returnDataSetField = value;
                this.RaisePropertyChanged("ReturnDataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ReturnMsg {
            get {
                return this.returnMsgField;
            }
            set {
                this.returnMsgField = value;
                this.RaisePropertyChanged("ReturnMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ReturnMsgNo {
            get {
                return this.returnMsgNoField;
            }
            set {
                this.returnMsgNoField = value;
                this.RaisePropertyChanged("ReturnMsgNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnMsgNoSpecified {
            get {
                return this.returnMsgNoFieldSpecified;
            }
            set {
                this.returnMsgNoFieldSpecified = value;
                this.RaisePropertyChanged("ReturnMsgNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ReturnSn {
            get {
                return this.returnSnField;
            }
            set {
                this.returnSnField = value;
                this.RaisePropertyChanged("ReturnSn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnSnSpecified {
            get {
                return this.returnSnFieldSpecified;
            }
            set {
                this.returnSnFieldSpecified = value;
                this.RaisePropertyChanged("ReturnSnSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="View_MyCard_SaveByCardBetweenQuery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class View_MyCard_SaveByCardBetweenQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CardNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Sn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActID;
        
        public View_MyCard_SaveByCardBetweenQueryRequest() {
        }
        
        public View_MyCard_SaveByCardBetweenQueryRequest(string CardNo, string Sn, string ActID) {
            this.CardNo = CardNo;
            this.Sn = Sn;
            this.ActID = ActID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="View_MyCard_SaveByCardBetweenQueryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class View_MyCard_SaveByCardBetweenQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SimpleTest.MyCardNoSetWCF.ReturnValue View_MyCard_SaveByCardBetweenQueryResult;
        
        public View_MyCard_SaveByCardBetweenQueryResponse() {
        }
        
        public View_MyCard_SaveByCardBetweenQueryResponse(SimpleTest.MyCardNoSetWCF.ReturnValue View_MyCard_SaveByCardBetweenQueryResult) {
            this.View_MyCard_SaveByCardBetweenQueryResult = View_MyCard_SaveByCardBetweenQueryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyCard_SaveByCardBetweenInsert", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MyCard_SaveByCardBetweenInsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_cCardStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_cCardEnd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_cActID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_cCreateUser;
        
        public MyCard_SaveByCardBetweenInsertRequest() {
        }
        
        public MyCard_SaveByCardBetweenInsertRequest(string P_cCardStart, string P_cCardEnd, string P_cActID, string P_cCreateUser) {
            this.P_cCardStart = P_cCardStart;
            this.P_cCardEnd = P_cCardEnd;
            this.P_cActID = P_cActID;
            this.P_cCreateUser = P_cCreateUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyCard_SaveByCardBetweenInsertResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MyCard_SaveByCardBetweenInsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SimpleTest.MyCardNoSetWCF.ReturnValueIns MyCard_SaveByCardBetweenInsertResult;
        
        public MyCard_SaveByCardBetweenInsertResponse() {
        }
        
        public MyCard_SaveByCardBetweenInsertResponse(SimpleTest.MyCardNoSetWCF.ReturnValueIns MyCard_SaveByCardBetweenInsertResult) {
            this.MyCard_SaveByCardBetweenInsertResult = MyCard_SaveByCardBetweenInsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyCard_SaveByCardBetweenUpdate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MyCard_SaveByCardBetweenUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int P_iSn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int P_iStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_cProcDesc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_cCreateUser;
        
        public MyCard_SaveByCardBetweenUpdateRequest() {
        }
        
        public MyCard_SaveByCardBetweenUpdateRequest(int P_iSn, int P_iStatus, string P_cProcDesc, string P_cCreateUser) {
            this.P_iSn = P_iSn;
            this.P_iStatus = P_iStatus;
            this.P_cProcDesc = P_cProcDesc;
            this.P_cCreateUser = P_cCreateUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyCard_SaveByCardBetweenUpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MyCard_SaveByCardBetweenUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SimpleTest.MyCardNoSetWCF.ReturnValue MyCard_SaveByCardBetweenUpdateResult;
        
        public MyCard_SaveByCardBetweenUpdateResponse() {
        }
        
        public MyCard_SaveByCardBetweenUpdateResponse(SimpleTest.MyCardNoSetWCF.ReturnValue MyCard_SaveByCardBetweenUpdateResult) {
            this.MyCard_SaveByCardBetweenUpdateResult = MyCard_SaveByCardBetweenUpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SimpleTest.MyCardNoSetWCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SimpleTest.MyCardNoSetWCF.IService1>, SimpleTest.MyCardNoSetWCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpleTest.MyCardNoSetWCF.View_MyCard_SaveByCardBetweenQueryResponse SimpleTest.MyCardNoSetWCF.IService1.View_MyCard_SaveByCardBetweenQuery(SimpleTest.MyCardNoSetWCF.View_MyCard_SaveByCardBetweenQueryRequest request) {
            return base.Channel.View_MyCard_SaveByCardBetweenQuery(request);
        }
        
        public SimpleTest.MyCardNoSetWCF.ReturnValue View_MyCard_SaveByCardBetweenQuery(string CardNo, string Sn, string ActID) {
            SimpleTest.MyCardNoSetWCF.View_MyCard_SaveByCardBetweenQueryRequest inValue = new SimpleTest.MyCardNoSetWCF.View_MyCard_SaveByCardBetweenQueryRequest();
            inValue.CardNo = CardNo;
            inValue.Sn = Sn;
            inValue.ActID = ActID;
            SimpleTest.MyCardNoSetWCF.View_MyCard_SaveByCardBetweenQueryResponse retVal = ((SimpleTest.MyCardNoSetWCF.IService1)(this)).View_MyCard_SaveByCardBetweenQuery(inValue);
            return retVal.View_MyCard_SaveByCardBetweenQueryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenInsertResponse SimpleTest.MyCardNoSetWCF.IService1.MyCard_SaveByCardBetweenInsert(SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenInsertRequest request) {
            return base.Channel.MyCard_SaveByCardBetweenInsert(request);
        }
        
        public SimpleTest.MyCardNoSetWCF.ReturnValueIns MyCard_SaveByCardBetweenInsert(string P_cCardStart, string P_cCardEnd, string P_cActID, string P_cCreateUser) {
            SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenInsertRequest inValue = new SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenInsertRequest();
            inValue.P_cCardStart = P_cCardStart;
            inValue.P_cCardEnd = P_cCardEnd;
            inValue.P_cActID = P_cActID;
            inValue.P_cCreateUser = P_cCreateUser;
            SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenInsertResponse retVal = ((SimpleTest.MyCardNoSetWCF.IService1)(this)).MyCard_SaveByCardBetweenInsert(inValue);
            return retVal.MyCard_SaveByCardBetweenInsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenUpdateResponse SimpleTest.MyCardNoSetWCF.IService1.MyCard_SaveByCardBetweenUpdate(SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenUpdateRequest request) {
            return base.Channel.MyCard_SaveByCardBetweenUpdate(request);
        }
        
        public SimpleTest.MyCardNoSetWCF.ReturnValue MyCard_SaveByCardBetweenUpdate(int P_iSn, int P_iStatus, string P_cProcDesc, string P_cCreateUser) {
            SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenUpdateRequest inValue = new SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenUpdateRequest();
            inValue.P_iSn = P_iSn;
            inValue.P_iStatus = P_iStatus;
            inValue.P_cProcDesc = P_cProcDesc;
            inValue.P_cCreateUser = P_cCreateUser;
            SimpleTest.MyCardNoSetWCF.MyCard_SaveByCardBetweenUpdateResponse retVal = ((SimpleTest.MyCardNoSetWCF.IService1)(this)).MyCard_SaveByCardBetweenUpdate(inValue);
            return retVal.MyCard_SaveByCardBetweenUpdateResult;
        }
    }
}
