//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.18408。
// 
#pragma warning disable 1591

namespace SimpleTest.PortalLogReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsWorkLogSoap", Namespace="http://tempuri.org/")]
    public partial class wsWorkLog : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertWorkLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertWLogOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsWorkLog() {
            this.Url = global::SimpleTest.Properties.Settings.Default.SimpleTest_PortalLogReference_wsWorkLog;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertWorkLogCompletedEventHandler InsertWorkLogCompleted;
        
        /// <remarks/>
        public event InsertWLogCompletedEventHandler InsertWLogCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertWorkLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertWorkLog(string Users, string CreateIp, string sCurrentUrl, System.Data.DataTable PageInfo, string sFounction) {
            object[] results = this.Invoke("InsertWorkLog", new object[] {
                        Users,
                        CreateIp,
                        sCurrentUrl,
                        PageInfo,
                        sFounction});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertWorkLogAsync(string Users, string CreateIp, string sCurrentUrl, System.Data.DataTable PageInfo, string sFounction) {
            this.InsertWorkLogAsync(Users, CreateIp, sCurrentUrl, PageInfo, sFounction, null);
        }
        
        /// <remarks/>
        public void InsertWorkLogAsync(string Users, string CreateIp, string sCurrentUrl, System.Data.DataTable PageInfo, string sFounction, object userState) {
            if ((this.InsertWorkLogOperationCompleted == null)) {
                this.InsertWorkLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertWorkLogOperationCompleted);
            }
            this.InvokeAsync("InsertWorkLog", new object[] {
                        Users,
                        CreateIp,
                        sCurrentUrl,
                        PageInfo,
                        sFounction}, this.InsertWorkLogOperationCompleted, userState);
        }
        
        private void OnInsertWorkLogOperationCompleted(object arg) {
            if ((this.InsertWorkLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertWorkLogCompleted(this, new InsertWorkLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertWLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertWLog(string Users, string CreateIp, string sContents, string sFounction) {
            object[] results = this.Invoke("InsertWLog", new object[] {
                        Users,
                        CreateIp,
                        sContents,
                        sFounction});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertWLogAsync(string Users, string CreateIp, string sContents, string sFounction) {
            this.InsertWLogAsync(Users, CreateIp, sContents, sFounction, null);
        }
        
        /// <remarks/>
        public void InsertWLogAsync(string Users, string CreateIp, string sContents, string sFounction, object userState) {
            if ((this.InsertWLogOperationCompleted == null)) {
                this.InsertWLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertWLogOperationCompleted);
            }
            this.InvokeAsync("InsertWLog", new object[] {
                        Users,
                        CreateIp,
                        sContents,
                        sFounction}, this.InsertWLogOperationCompleted, userState);
        }
        
        private void OnInsertWLogOperationCompleted(object arg) {
            if ((this.InsertWLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertWLogCompleted(this, new InsertWLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void InsertWorkLogCompletedEventHandler(object sender, InsertWorkLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertWorkLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertWorkLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void InsertWLogCompletedEventHandler(object sender, InsertWLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertWLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertWLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591